### ISSUE TITLE
Problem of Data Parallel Model,  program didn't end when reached global step

### ISSUE THREAD

**Issue by Jimmy-jin** [alibaba/EasyParallelLibrary#20]
I got a problem when using EPL data parallel Model. 
The num worker is set to 3 and each worker had its own TF data record  input and Model save_dir. The global step is set to 3500 for each  worker. It seems normal when  global step was below 3500, but the program not  end when reached 3500.  Seems like the chief worker 0 didn't  know other worker  was end。

![image](https://user-images.githubusercontent.com/17492085/182804804-8bfec56f-dc4b-40d6-b0cd-b791adab5ae0.png)

**Comment by adoda** [comment]
Could you provide a example and your script?
